# Generated by Django 4.1.7 on 2023-03-29 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=256)),
                ('filmImage', models.ImageField(upload_to='images/')),
                ('duration', models.CharField(max_length=6)),
                ('age', models.CharField(choices=[('U', 'U'), ('PG', 'PG'), ('12A', '12A'), ('12', '12'), ('15', '15'), ('18', '18')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='showing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of showing (mm/dd/yyyy)')),
                ('startTime', models.TimeField(verbose_name='Time of showing (HH:MM)')),
                ('numberOfSales', models.IntegerField(blank=True, null=True)),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema.film')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.screen')),
            ],
        ),
        migrations.CreateModel(
            name='seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.row')),
            ],
        ),
        migrations.AddField(
            model_name='row',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.screen'),
        ),
    ]
