# Generated by Django 4.1.7 on 2023-03-18 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('ageRating', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=256)),
                ('trailer', models.TextField(max_length=550, default='null')),
                ('year', models.CharField(max_length=4)),
                ('rating', models.CharField(max_length=3)),
                ('duration', models.IntegerField()),
            
            ],
        ),
        migrations.CreateModel(
            name='row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='showing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('numberOfSales', models.IntegerField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.film')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.screen')),
            ],
        ),
        migrations.CreateModel(
            name='seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.row')),
            ],
        ),
        migrations.AddField(
            model_name='row',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.screen'),
        ),
    ]
