# Generated by Django 4.1.7 on 2023-03-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_remove_film_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='filmImage',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
