# Generated by Django 4.1.7 on 2023-03-20 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_film_filmimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showing',
            name='dateTime',
        ),
        migrations.AddField(
            model_name='showing',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='showing',
            name='startTime',
            field=models.TimeField(default=datetime.datetime(2023, 3, 20, 19, 3, 4, 939992)),
        ),
    ]
