# Generated by Django 4.1.7 on 2023-03-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_alter_showing_date_alter_showing_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showing',
            name='date',
            field=models.DateField(verbose_name='Date of showing (mm/dd/yyyy)'),
        ),
        migrations.AlterField(
            model_name='showing',
            name='numberOfSales',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='showing',
            name='startTime',
            field=models.TimeField(verbose_name='Time of showing (HH:MM)'),
        ),
    ]
