# Generated by Django 4.1.5 on 2023-03-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_remove_film_agerating_film_age_alter_film_filmimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='filmImage',
            field=models.ImageField(upload_to='uweflix/cinema/static/images/'),
        ),
    ]
