# Generated by Django 4.1.5 on 2023-03-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_alter_film_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='age',
            field=models.IntegerField(choices=[('U', 'U'), ('PG', 'PG'), ('12A', '12A'), ('12', '12'), ('15', '15'), ('18', '18')], default=5),
        ),
    ]
