# Generated by Django 4.1.4 on 2023-03-30 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0017_alter_showing_film'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('student_tickets', models.IntegerField(default=0)),
                ('child_tickets', models.IntegerField(default=0)),
                ('adult_tickets', models.IntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('showing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.showing')),
            ],
        ),
    ]
