# Generated by Django 4.1.4 on 2023-04-09 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0018_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='trailer',
        ),
    ]
