# Generated by Django 4.1.4 on 2023-04-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0019_remove_film_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='trailer',
            field=models.TextField(default='null', max_length=550),
        ),
    ]
