# Generated by Django 4.1.4 on 2023-04-20 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_usertype'),
        ('cinema', '0022_booking_cr_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='accounts.user'),
        ),
    ]
