# Generated by Django 4.1.4 on 2023-05-01 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0025_alter_booking_adult_tickets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cr_tickets',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
