# Generated by Django 4.1.4 on 2023-05-08 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0028_booking_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cr_tickets',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
