# Generated by Django 4.1.4 on 2023-05-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0029_alter_booking_cr_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cr_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
