# Generated by Django 4.1.7 on 2023-03-29 16:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TicketBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_date', models.DateField(default=django.utils.timezone.now)),
                ('ticket_count', models.IntegerField()),
                ('ticket_type', models.CharField(choices=[('Student', 'Student'), ('Child', 'Child'), ('Adult', 'Adult')], max_length=15)),
                ('showing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.showing')),
            ],
        ),
    ]
