# Generated by Django 4.1.4 on 2023-03-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketbooking',
            name='ticket_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Child', 'Child'), ('Adult', 'Adult')], max_length=15),
        ),
    ]
