# Generated by Django 4.1.4 on 2023-03-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_ticketbooking_ticket_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='ticketbooking',
            name='credit_card_exp',
        ),
        migrations.RemoveField(
            model_name='ticketbooking',
            name='credit_card_info',
        ),
        migrations.RemoveField(
            model_name='ticketbooking',
            name='credit_card_name',
        ),
        migrations.RemoveField(
            model_name='ticketbooking',
            name='status',
        ),
    ]
