# Generated by Django 4.1.4 on 2023-03-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubRep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
