# Generated by Django 4.1.4 on 2023-04-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubRep', '0002_club_balance_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='landlineNo',
            field=models.IntegerField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='mobileNo',
            field=models.IntegerField(max_length=11, null=True),
        ),
    ]
