# Generated by Django 4.1.4 on 2023-04-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubRep', '0003_alter_club_landlineno_alter_club_mobileno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='landlineNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='mobileNo',
            field=models.IntegerField(null=True),
        ),
    ]
