# Generated by Django 4.1.4 on 2023-05-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubRep', '0004_alter_club_landlineno_alter_club_mobileno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
