# Generated by Django 4.1.7 on 2023-03-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('S', 'Student'), ('CR', 'Club Rep'), ('AM', 'Accounts Manager'), ('CM', 'Cinema Manager')], default='S', max_length=2),
        ),
    ]
