# Generated by Django 4.1.7 on 2023-03-30 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubRep', '0002_club_balance_transaction'),
        ('accounts', '0003_alter_user_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='affiliatedClub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubRep.club'),
        ),
    ]
