# Generated by Django 4.1.4 on 2023-04-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_affiliatedclub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('C', 'Customer'), ('S', 'Student'), ('CR', 'Club Rep'), ('AM', 'Accounts Manager'), ('CM', 'Cinema Manager')], default='C', max_length=2),
        ),
    ]
