# Generated by Django 4.1.4 on 2023-05-01 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(-150)]),
        ),
    ]
