# Generated by Django 4.1.4 on 2023-05-01 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-150)]),
        ),
    ]
