# Generated by Django 4.1.4 on 2023-05-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_transaction'),
        ('accounts', '0008_user_activated'),
    ]

    operations = [
    ]
